# This is a basic workflow to help you get started with Actions

name: FishPond Monitor

# A workflow run is made up of one or more jobs that can run sequentially or in parallel

runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
#     - id: version
#       uses: pozetroninc/github-action-get-latest-release@master
#       with:
#         repository: ImYrS/aliyun-auto-signin
#         excludes: prerelease, draft
    - name: Download
      shell: bash
      run: |
        wget https://raw.githubusercontent.com/dawn997/jiankong/main/test.py
    - name: Run
      shell: bash
      run: |
        python test.py
      env:
        env:
            TOKEN:${{ secrets.TOKEN }}

          
#         run: |
#           echo Add other actions to build,
#           echo test, and deploy your project.
      
#       - name: Download
#         shell: bash
#         run: |
#           #https://github.com/dawn997/jiankong.git
#           wget https://codeload.github.com/dawn997/jiankong/zip/refs/heads/main -O release.zip
#           rm -rf release
#           unzip release.zip -d release
#           rm release.zip
