# This is a basic workflow to help you get started with Actions

name: FishPond Monitor

on:
  schedule:
   # 每天国际时间 17:20 运行一次, 中国时间 01:20
    - cron: '20 17 * * *'
  workflow_dispatch:

# on:
#   push:
#     branches: [ "master" ]
#   pull_request:
#     branches: [ "master" ]

jobs:
  sigin:
    name: FishPond Monitor
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Download
      shell: bash
      run: |
        wget https://github.com/dawn997/jiankong/archive/refs/tags/v1.0.zip -O release.zip
        rm -rf release
        unzip release.zip -d release
        rm release.zip
    - name : Run
      shell: bash
      run: |
        cd release
        cd $(ls -dt */|head -1 )
        pip install requests
        python post_url.py
#        pip install numpy
#        pip install alibabacloud_facebody20191230
#        pip install alibabacloud_tea_openapi
#        pip install alibabacloud_tea_util
#        pip install pip install opencv-python
#        pip install paramiko
        
      env:
        TOKEN: ${{ secrets.TOKEN }}
        ALI_ACCESS_KEY_SECRET: ${{ secrets.ALI_ACCESS_KEY_SECRET }}
        ALI_ACCESS_KEY_ID: ${{ secrets.ALI_ACCESS_KEY_ID }}
        CAM_IP: ${{ secrets.CAM_IP }}
        CAM_PASSWORD: ${{ secrets.CAM_PASSWORD }}
        IMAGE_URL: ${{ secrets.IMAGE_URL }}
        VPS_IP: ${{ secrets.VPS_IP }}
        VPS_PASSWORD: ${{ secrets.VPS_PASSWORD }}
        WX_PUSH_APPTOKEN: ${{ secrets.WX_PUSH_APPTOKEN }}
        WX_PUSH_UID: ${{ secrets.WX_PUSH_UID }}
        #ALI_ACCESS_KEY_ID=LTAI5tLHrEnaYZUsEYXrswfE;
#         ALI_ACCESS_KEY_SECRET=gbFw9GHG9pov7NOUtJRrZXwvLfUHoA;
#         CAM_IP=dawn97.tpddns.cn;
#         CAM_PASSWORD=wx199712;
#         IMAGE_URL=http://test.luckytnt.top:8881/map/;
#         VPS_IP=107.172.86.106;
#         VPS_PASSWORD=I1Q0xNO6j0kxyQJg67;
#         WX_PUSH_APPTOKEN=AT_BA8E2Mfd8vRwuiWlbnAMQnx20EaFwgdp;
#         WX_PUSH_UID=UID_E0zrUrJZVMMQvglmg6VRys376cqo
        

